name: Test
on:
  workflow_dispatch:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17']
        os: [ubuntu-latest]
    steps:

    - name: Check out repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0

    - name: Check out target repository
      run: |
          git clone https://github.com/behnazh-w/example-maven-app

    # Install Java.
    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
        cache: maven

    - name: Install Witness
      run: |
        wget https://github.com/in-toto/witness/releases/download/v0.3.1/witness_0.3.1_linux_amd64.tar.gz
        tar -xf witness_0.3.1_linux_amd64.tar.gz
        openssl genpkey -algorithm ed25519 -outform PEM -out testkey.pem
        openssl pkey -in testkey.pem -pubout > testpub.pem

    - name: Build
      run: |
        cp .witness.yaml ./example-maven-app/
        cd example-maven-app
        ../witness run --step build -o test-att.json --attestor-product-include-glob target/* -a git -a maven ./mvnw clean package

    - name: upload
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: test-att.json
        path: ./example-maven-app/test-att.json

